---
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install devel packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libtool
    - automake
    - libbz2-dev
    - libsqlite3-dev
    - libncurses-dev
    - libreadline-dev
    - libffi-dev
    - tk-dev
    - liblzma-dev
    - libssl-dev
    - python-openssl
