---
- name: Test testboxes
  hosts: test

  vars:
    mymsg: "Hello, MyMSG"
    mymsg2:
      name1: "Hello"
      name2: "MyMSG"

  tasks:
    - name: mymsg
      debug:
        msg: "Msg is {{ mymsg }}"

    - name: mymsg2
      debug:
        msg: "Msg is {{ mymsg2.name1 }} and {{ mymsg2.name2 }}"

    - name: mymsg2-1
      debug:
        msg: "Msg is {{ mymsg2['name1'] }} and {{ mymsg2['name2'] }}"
